baseURL: https://andrew-robak-portfolio.netlify.app/
languageCode: en-us
title: Portfolio website for Andrew Robak
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    image:
    buttonText: Learn more about me
    #subtitle: |-
      #A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
      #AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Andrew!
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: arobak.mam2023@london.edu
    enable: yes
    phone:
      - phone: available upon request
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Andrew Robak
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com/kostisc
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com/kostisc
      - icon: fa-github
        label: GitHub
        url: https://github.com/andrew-robak
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/jedrzej-robak/
  image: 'banner.jpg'
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: guitar.jpg
        subtitle: About me
        title: CV
        url: blogs/andrew_cv
      - image: stocks.jpg
        subtitle: R analysis
        title: Risk-Return of DJIA Stocks
        url: blogs/risk_return
      - image: biden.jpg
        subtitle: R analysis
        title: Biden's Approval Ratings
        url: blogs/biden_approval
      - image: bikes.jpg
        subtitle: R analysis
        title: Excess Rentals of Tfl Bikes
        url: blogs/london_bikes
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
#  two:
#    buttonText: Get in touch
#    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
#    title: Seems interesting?
#    url: blogs
